name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *  # 8 am IST
    - cron : 30 13 * * *  # 7:30 pm IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6-beta

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
          with:
            node-version: '22'

      - name: Install newman and Html-extrareport globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
          newman run 'Inwarrenty-flow Collection Data Variable.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra




            
      
      
            
            
        
      
