name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *  # 8 am IST
    - cron : 30 13 * * *  # 7:30 pm IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6-beta

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install newman and Html-extrareport globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
          newman run 'Inwarrenty-flow Collection Data Variable.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html
      
      - name: Newman report
        if: always()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman report
          path: newman/*.html

      - name: Creating Github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow execution notification
          to: ak47jerry612@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Please find the attached HTML report generated after running the postman test via Github Actions.
                Link to live report(GitHub pages): https://tushararban.github.io/Phoenix-Inwarranty-Flow/
                regards,
                GitHub Actions
                
          
          
          



            
      
      
            
            
        
      
